version: "3.7"

services:
  gateway:
    build:
      context: ./gateway
      dockerfile: ./build/Dockerfile
    ports:
      - "8800:8080"
      - "8801:8081"
    links:
      - auth
      - user
      - server
      - channel
      - chat

  auth:
    build:
      context: ./auth
      dockerfile: ./build/Dockerfile
    ports:
      - "8811:8080"

  user:
    build:
      context: ./user
      dockerfile: ./build/Dockerfile

  server:
    build:
      context: ./server
      dockerfile: ./build/Dockerfile

  channel:
    build:
      context: ./channel
      dockerfile: ./build/Dockerfile

  chat:
    build:
      context: ./chat
      dockerfile: ./build/Dockerfile

  mongodb-chat:
    image: mongo:7.0.5
    restart: unless-stopped
    env_file: ./chat/.env
    volumes:
      - mongo-volume:/data/db
    ports:
      - 27117:27017
    environment:
      - PUID=1000
      - PGID=1000
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB}

volumes:
  mongo-volume:
  cache:
    driver: local
