// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/Nixonxp/discord/chat/internal/app/models"
	mock "github.com/stretchr/testify/mock"
)

// ChatsStorage is an autogenerated mock type for the ChatsStorage type
type ChatsStorage struct {
	mock.Mock
}

// CreateMessage provides a mock function with given fields: _a0, message
func (_m *ChatsStorage) CreateMessage(_a0 context.Context, message *models.Message) (*models.Message, error) {
	ret := _m.Called(_a0, message)

	if len(ret) == 0 {
		panic("no return value specified for CreateMessage")
	}

	var r0 *models.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Message) (*models.Message, error)); ok {
		return rf(_a0, message)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Message) *models.Message); ok {
		r0 = rf(_a0, message)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Message) error); ok {
		r1 = rf(_a0, message)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMessages provides a mock function with given fields: _a0, userId, chatId
func (_m *ChatsStorage) GetMessages(_a0 context.Context, userId uint64, chatId uint64) ([]*models.Message, error) {
	ret := _m.Called(_a0, userId, chatId)

	if len(ret) == 0 {
		panic("no return value specified for GetMessages")
	}

	var r0 []*models.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64) ([]*models.Message, error)); ok {
		return rf(_a0, userId, chatId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64) []*models.Message); ok {
		r0 = rf(_a0, userId, chatId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, uint64) error); ok {
		r1 = rf(_a0, userId, chatId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewChatsStorage creates a new instance of ChatsStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChatsStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChatsStorage {
	mock := &ChatsStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
