// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CallbackOAuthUserRequest callback o auth user request
//
// swagger:model CallbackOAuthUserRequest
type CallbackOAuthUserRequest struct {

	// code
	// Example: 9HqLlyZOugoStsXCUfD_0YdwnNnunAJF8V47U3QHXSq
	// Required: true
	Code *string `json:"code"`
}

// Validate validates this callback o auth user request
func (m *CallbackOAuthUserRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCode(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CallbackOAuthUserRequest) validateCode(formats strfmt.Registry) error {

	if err := validate.Required("code", "body", m.Code); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this callback o auth user request based on context it is used
func (m *CallbackOAuthUserRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CallbackOAuthUserRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CallbackOAuthUserRequest) UnmarshalBinary(b []byte) error {
	var res CallbackOAuthUserRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
