// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// LoginOAthUserResponse login o ath user response
//
// swagger:model LoginOAthUserResponse
type LoginOAthUserResponse struct {

	// code
	// Example: 9HqLlyZOugoStsXCUfD_0YdwnNnunAJF8V47U3QHXSq
	Code string `json:"code,omitempty"`
}

// Validate validates this login o ath user response
func (m *LoginOAthUserResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this login o ath user response based on context it is used
func (m *LoginOAthUserResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LoginOAthUserResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LoginOAthUserResponse) UnmarshalBinary(b []byte) error {
	var res LoginOAthUserResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
