// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RegisterUserResponse register user response
//
// swagger:model RegisterUserResponse
type RegisterUserResponse struct {

	// email
	// Example: user123@mail.ru
	Email string `json:"email,omitempty"`

	// id
	// Example: 1
	ID int64 `json:"id,omitempty"`

	// login
	// Example: user_login
	Login string `json:"login,omitempty"`

	// name
	// Example: user123
	Name string `json:"name,omitempty"`
}

// Validate validates this register user response
func (m *RegisterUserResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this register user response based on context it is used
func (m *RegisterUserResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RegisterUserResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RegisterUserResponse) UnmarshalBinary(b []byte) error {
	var res RegisterUserResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
