apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-1.2
  namespace: discord-app
  labels:
    app: auth
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
        version: "1.2"
    spec:
      containers:
        - name: auth-container
          image: docker.io/library/discord-app-auth:v2
          imagePullPolicy: "Never" # for local in minikube
          ports:
            - containerPort: 8080
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10