apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: discord-app
spec:
  type: LoadBalancer
  selector:
    app: auth
    version: "1.1"
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080