// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	pgx "github.com/jackc/pgx/v5"
	mock "github.com/stretchr/testify/mock"
)

// TransactionManager is an autogenerated mock type for the TransactionManager type
type TransactionManager struct {
	mock.Mock
}

// RunReadCommitted provides a mock function with given fields: ctx, accessMode, f
func (_m *TransactionManager) RunReadCommitted(ctx context.Context, accessMode pgx.TxAccessMode, f func(context.Context) error) error {
	ret := _m.Called(ctx, accessMode, f)

	if len(ret) == 0 {
		panic("no return value specified for RunReadCommitted")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.TxAccessMode, func(context.Context) error) error); ok {
		r0 = rf(ctx, accessMode, f)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTransactionManager creates a new instance of TransactionManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionManager {
	mock := &TransactionManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
